name = "dump-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CLIPBOARD_KV"
id = "712aa3fe5dbb4830a492d0f26281d485"
preview_id = "c69629bd6f0348b4ae1f4ae8b0b8eda6"
