#!/bin/bash
echo "=== Manual Testing Instructions for TASK-017 ==="
echo ""
echo "Test 1 — View public clipboard:"
echo "  1. Create a public clipboard via UI or API."
echo "  2. Navigate to /:code → content displayed."
echo ""
echo "Test 2 — View nonexistent clipboard:"
echo "  1. Navigate to /invalidcode123"
echo "  2. → 'Clipboard not found or expired' message should appear."
echo ""
echo "Test 3 — View locked clipboard:"
echo "  1. Create a protected clipboard with a password."
echo "  2. Navigate to /:code (in an incognito window or clear token from localStorage)."
echo "  3. → password prompt shown."
echo "  4. Enter wrong password → error shown."
echo "  5. Enter correct password → content shown."
echo ""
echo "Test 4 — View with owner token (no prompt):"
echo "  1. Create a protected clipboard."
echo "  2. Navigate to /:code in the same browser (owner token in localStorage)."
echo "  3. → content shown without password prompt."
echo ""
echo "Test 5 — One-time view message:"
echo "  1. Create a public clipboard with one-time view enabled."
echo "  2. Navigate to /:code"
echo "  3. → content shown with deletion message ('This was a one-time view clipboard...')."
echo ""
echo "Test 6 — Star/unstar:"
echo "  1. Create a public clipboard."
echo "  2. Navigate to /:code"
echo "  3. Click Star → button changes to Unstar, Starred status changes to Yes."
echo "  4. Click Unstar → button changes back."
echo ""
echo "Make sure the backend is running locally!"
echo "cd apps/dump-web && npm run dev"
